name: Baileys Edge Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update baileys
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run baileys edge
        uses: hansputera/Baileys-edge@master
        with:
          cloneDir: baileys
          checkFile: baileys_check.json
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
